version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - karelhala
  - ryelo
  allow:
  - dependency-name: "@redhat-cloud-services/frontend*"
  - dependency-name: "@patternfly/*"
    dependency-type: direct
  - dependency-name: react
    dependency-type: direct
  - dependency-name: react-dom
    dependency-type: direct
  ignore:
  - dependency-name: "@patternfly/react-icons"
    versions:
    - 4.10.1
    - 4.9.0
    - 4.9.1
  - dependency-name: "@patternfly/react-table"
    versions:
    - 4.20.15
    - 4.23.0
    - 4.23.1
    - 4.23.14
    - 4.23.2
    - 4.24.0
    - 4.24.1
    - 4.26.6
  - dependency-name: "@patternfly/react-core"
    versions:
    - 4.101.3
    - 4.106.1
    - 4.106.2
    - 4.115.1
    - 4.90.2
    - 4.97.0
    - 4.97.1
    - 4.97.2
  - dependency-name: "@redhat-cloud-services/frontend-components"
    versions:
    - 2.5.3
    - 3.1.10
    - 3.1.5
    - 3.1.6
    - 3.1.9
  - dependency-name: "@redhat-cloud-services/frontend-components-config"
    versions:
    - 3.0.0-beta12
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.15
    - 4.0.16
    - 4.0.17
    - 4.0.18
    - 4.0.19
    - 4.0.20
    - 4.0.21
    - 4.0.22
    - 4.0.23
    - 4.0.25
  - dependency-name: "@redhat-cloud-services/frontend-components-utilities"
    versions:
    - 3.1.0
  - dependency-name: "@patternfly/react-tokens"
    versions:
    - 4.10.0
    - 4.10.1
  - dependency-name: "@redhat-cloud-services/frontend-components-notifications"
    versions:
    - 3.0.2
